title: 5th Workshop on Document Analysis and Recognition
email: ravi.kiran@iiit.ac.in
description: Website for the 5th Workshop on Document Analysis and Recognition at ICVGIP 2021
  ---
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
include: ['_pages']
